import React from 'react';
import { Download, CheckCircle2, XCircle, AlertCircle, ArrowRight, User, Mail, GraduationCap, Clock, Award, ShieldCheck } from 'lucide-react';
import jsPDF from 'jspdf';
import { useAuth } from '../context/AuthContext';
import { calculateClientGapAnalysis, extractFlatUserSkills } from '../utils/skillMatcher';

export default function ResumeResultView({
  analysisData,
  onNavigateToSkills,
  onNavigateToGap,
  onNavigateToSuggestions,
}) {
  const { user, showToast } = useAuth();

  const data = analysisData || {};
  const targetRole = data.targetRole || { roleId: 'software-developer', title: 'Software Developer' };
  const rawSkills = data.extractedSkills || data.userSkills || {
    technical: [],
    soft: [],
    tools: [],
    cloudAndDb: [],
  };

  const live = calculateClientGapAnalysis(rawSkills, targetRole.roleId);

  const candidateInfo = data.candidateInfo || {
    name: 'Candidate',
    email: 'Not found',
    experience: 'Not specified',
    education: 'Not specified',
  };

  const matchedSkills = live.matchedSkills;
  const missingSkills = live.missingSkills;
  const partialSkills = live.partialSkills;
  const matchScore = live.matchScore;
  
  const matchedCount = live.summaryStats.matchedCount;
  const missingCount = live.summaryStats.missingCount;
  const partialCount = live.summaryStats.partialCount;

  // Calculate SVG Circle Donut Dasharray
  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (matchScore / 100) * circumference;

  // Download PDF Report
  const handleDownloadReport = () => {
    try {
      const doc = new jsPDF();

      // Header Banner
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, 210, 38, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('Resume Skill Gap Analysis Report', 14, 20);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated on: ${new Date().toLocaleDateString()} | Target Role: ${targetRole.title}`, 14, 29);

      // Candidate Information Section
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('1. Candidate Information', 14, 52);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Name: ${candidateInfo.name}`, 14, 62);
      doc.text(`Email: ${candidateInfo.email}`, 14, 70);
      doc.text(`Experience: ${candidateInfo.experience}`, 14, 78);
      doc.text(`Education: ${candidateInfo.education}`, 14, 86);

      // Score Summary Box
      doc.setFillColor(239, 246, 255);
      doc.rect(120, 48, 76, 42, 'F');
      doc.setTextColor(37, 99, 235);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(`${matchScore}%`, 130, 68);
      doc.setFontSize(10);
      doc.text('Overall Role Match', 130, 78);

      // Skills Breakdown
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.text('2. Skill Gap Breakdown', 14, 105);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(16, 185, 129);
      doc.text(`Matched Skills (${matchedCount}):`, 14, 115);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      doc.text(matchedSkills.join(', ') || 'None', 14, 123, { maxWidth: 180 });

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(239, 68, 68);
      doc.text(`Missing Skills (${missingCount}):`, 14, 137);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      doc.text(missingSkills.join(', ') || '🎉 100% Core Requirements Matched! (None Missing)', 14, 145, { maxWidth: 180 });

      // Recommendations
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('3. Curated Learning Recommendations', 14, 165);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      let yPos = 175;
      if (missingSkills.length === 0) {
        doc.setFont('helvetica', 'italic');
        doc.text('Candidate satisfies 100% of core role competencies. No remedial course needed.', 14, yPos);
      } else {
        data.recommendations?.forEach((rec) => {
          doc.setFont('helvetica', 'bold');
          doc.text(`• Learn ${rec.skill}`, 14, yPos);
          doc.setFont('helvetica', 'normal');
          doc.text(rec.description || '', 18, yPos + 6, { maxWidth: 170 });
          yPos += 14;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('Generated by Resume Skill Gap Analyzer | Connected to MongoDB Database', 14, 285);

      doc.save(`${(candidateInfo.name || 'Candidate').replace(/\s+/g, '_')}_Skill_Gap_Report.pdf`);
      showToast('PDF Report downloaded successfully!', 'success');
    } catch (err) {
      showToast('Downloaded report summary', 'info');
      window.print();
    }
  };

  return (
    <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
      {/* Top Header matching prototype screen 6 */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '1.75rem',
          flexWrap: 'wrap',
          gap: '1rem',
        }}
      >
        <div>
          <h2 style={{ fontSize: '1.85rem', color: '#0f172a', marginBottom: '0.25rem' }}>
            Resume Analysis Result
          </h2>
          <p style={{ color: '#64748b', fontSize: '0.95rem' }}>
            Target Role: <strong style={{ color: '#2563eb' }}>{targetRole.title}</strong>
          </p>
        </div>

        <button
          onClick={handleDownloadReport}
          className="btn-primary"
          style={{ padding: '0.65rem 1.4rem' }}
        >
          <Download size={17} />
          <span>Download Report</span>
        </button>
      </div>

      {/* Two Column Grid matching prototype Screen 6 */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.5rem', marginBottom: '2rem' }}>
        {/* Left Card: Candidate Information */}
        <div className="card">
          <h3
            style={{
              fontSize: '1.2rem',
              color: '#0f172a',
              marginBottom: '1.5rem',
              paddingBottom: '0.75rem',
              borderBottom: '1px solid #f1f5f9',
            }}
          >
            Candidate Information
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
              <span style={{ color: '#64748b', fontSize: '0.92rem', fontWeight: 500 }}>Name</span>
              <span style={{ color: '#0f172a', fontWeight: 600, fontSize: '0.95rem' }}>
                {candidateInfo.name || user?.name || 'Candidate'}
              </span>
            </div>

            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
              <span style={{ color: '#64748b', fontSize: '0.92rem', fontWeight: 500 }}>Email</span>
              <span style={{ color: '#0f172a', fontWeight: 600, fontSize: '0.95rem' }}>
                {candidateInfo.email || user?.email || 'Not Specified'}
              </span>
            </div>

            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
              <span style={{ color: '#64748b', fontSize: '0.92rem', fontWeight: 500 }}>Experience</span>
              <span style={{ color: '#0f172a', fontWeight: 600, fontSize: '0.95rem' }}>
                {candidateInfo.experience || 'Not Specified'}
              </span>
            </div>

            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
              <span style={{ color: '#64748b', fontSize: '0.92rem', fontWeight: 500 }}>Education</span>
              <span style={{ color: '#0f172a', fontWeight: 600, fontSize: '0.95rem', textAlign: 'right', maxWidth: '200px' }}>
                {candidateInfo.education || 'Not Specified'}
              </span>
            </div>
          </div>
        </div>

        {/* Right Card: Overall Skill Match Donut Meter (Matching Screen 6) */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <h3
            style={{
              fontSize: '1.2rem',
              color: '#0f172a',
              marginBottom: '1.25rem',
              paddingBottom: '0.75rem',
              borderBottom: '1px solid #f1f5f9',
            }}
          >
            Overall Skill Match
          </h3>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-around', gap: '1.5rem', flexWrap: 'wrap' }}>
            {/* Donut Score Meter with SVG Gradient */}
            <div className="score-circle-container">
              <svg className="score-circle-svg" viewBox="0 0 140 140">
                <defs>
                  <linearGradient id="scoreGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stopColor="#10b981" />
                    <stop offset="100%" stopColor="#3b82f6" />
                  </linearGradient>
                </defs>
                <circle className="score-circle-bg" cx="70" cy="70" r={radius} />
                <circle
                  className="score-circle-progress"
                  cx="70"
                  cy="70"
                  r={radius}
                  strokeDasharray={circumference}
                  strokeDashoffset={strokeDashoffset}
                />
              </svg>

              <div className="score-circle-text">
                <span className="score-circle-number">{matchScore}%</span>
                <span className="score-circle-label">MATCH</span>
              </div>
            </div>

            {/* Match Stats Legend matching prototype */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <span style={{ width: '12px', height: '12px', borderRadius: '50%', background: '#10b981' }} />
                <span style={{ fontSize: '0.92rem', color: '#334155' }}>
                  Matched Skills: <b style={{ color: '#10b981' }}>{matchedCount}</b>
                </span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <span style={{ width: '12px', height: '12px', borderRadius: '50%', background: '#ef4444' }} />
                <span style={{ fontSize: '0.92rem', color: '#334155' }}>
                  Missing Skills: <b style={{ color: missingCount > 0 ? '#ef4444' : '#10b981' }}>{missingCount}</b>
                </span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <span style={{ width: '12px', height: '12px', borderRadius: '50%', background: '#f59e0b' }} />
                <span style={{ fontSize: '0.92rem', color: '#334155' }}>
                  Partial Match: <b style={{ color: '#d97706' }}>{partialCount}</b>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Action Navigation Buttons to Next Screens */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          gap: '1rem',
          marginTop: '1.5rem',
        }}
      >
        <button
          onClick={onNavigateToSkills}
          className="btn-secondary"
          style={{ padding: '0.9rem', justifyContent: 'space-between' }}
        >
          <span>View Extracted Skills (Screen 7)</span>
          <ArrowRight size={17} />
        </button>

        <button
          onClick={onNavigateToGap}
          className="btn-secondary"
          style={{ padding: '0.9rem', justifyContent: 'space-between' }}
        >
          <span>View Gap Matrix (Screen 8)</span>
          <ArrowRight size={17} />
        </button>

        <button
          onClick={onNavigateToSuggestions}
          className="btn-primary"
          style={{ padding: '0.9rem', justifyContent: 'space-between' }}
        >
          <span>View Learning Suggestions (Screen 9)</span>
          <ArrowRight size={17} />
        </button>
      </div>
    </div>
  );
}
